CREATE TABLE game_grades(id INTEGER PRIMARY KEY NOT NULL,title TEXT(20) NOT NULL);
CREATE TABLE games (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,grade INTEGER NOT NULL ,FOREIGN KEY (grade) REFERENCES game_grades(id));
CREATE TABLE game_items(id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,game_id INTEGER NOT NULL ,game_row INTEGER NOT NULL,game_column INTEGER NOT NULL,game_value  INTEGER NOT NULL,FOREIGN KEY (game_id) REFERENCES games(id));
CREATE TABLE records (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ,game_id INTEGER NOT NULL ,name TEXT(40) NOT NULL ,error_count INTEGER NOT NULL ,duration INTEGER NOT NULL  );
